CREATE TABLE MEMBER(
   ID VARCHAR2(50) NOT NULL,
   PWD VARCHAR2(50) NOT NULL,
   NICKNAME VARCHAR2(50) PRIMARY KEY,
   BIRTH VARCHAR2(10),
   GENDER VARCHAR2(6),
   EMAIL VARCHAR2(50) UNIQUE,
   AUTH NUMBER(1) NOT NULL
);

DROP TABLE MEMBER
CASCADE CONSTRAINTS;

select * from MEMBER;